"""bug_fix

Revision ID: 2c420301e271
Revises: 617ce4d78b15
Create Date: 2026-01-07 17:34:42.082997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c420301e271'
down_revision: Union[str, Sequence[str], None] = '617ce4d78b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # postgresql_using='id::integer' qismini qo'shing

    op.alter_column('rooms', 'id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer') # <--- SHU QATORNI QO'SHING

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
