"""Add waypoint_id and floor_id to rooms

Revision ID: 617ce4d78b15
Revises: f77286e762f1
Create Date: 2026-01-07 15:45:36.382751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617ce4d78b15'
down_revision: Union[str, Sequence[str], None] = 'f77286e762f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('rooms_floor_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'floors', ['floor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rooms', 'capacity')
    op.drop_column('rooms', 'building')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('building', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_floor_id_fkey'), 'rooms', 'floors', ['floor_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
