"""initial migration

Revision ID: f77286e762f1
Revises: 
Create Date: 2026-01-06 16:27:41.913304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77286e762f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('waypoints',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HALLWAY', 'ROOM', 'STAIRS', 'ELEVATOR', 'HALL', name='waypointtype'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('connects_to_floor', sa.Integer(), nullable=True),
    sa.Column('connects_to_waypoint', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['connects_to_floor'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoints_id'), 'waypoints', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('from_waypoint_id', sa.String(length=50), nullable=False),
    sa.Column('to_waypoint_id', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('waypoint_id', sa.String(length=50), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.add_column('rooms', sa.Column('waypoint_id', sa.String(50), nullable=True))
    op.add_column('rooms', sa.Column('floor_id', sa.Integer(), nullable=True))
    
    # Foreign key constraint qo'shish
    op.create_foreign_key(
        'fk_rooms_waypoint',
        'rooms', 'waypoints',
        ['waypoint_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_rooms_floor',
        'rooms', 'floors',
        ['floor_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_waypoints_id'), table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_constraint('fk_rooms_floor', 'rooms', type_='foreignkey')
    op.drop_constraint('fk_rooms_waypoint', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'floor_id')
    op.drop_column('rooms', 'waypoint_id')

    # ### end Alembic commands ###
